[bot]
guild = 275819886553333762

[channels]
logs = 452953206264168458
modLogs = 452944195821371415

[roles]
mod = 452935318157393931
he_him = 830099878579011664
he_they = 830099911625801798
she_her = 830099939903275020
she_they = 830099985486839868
they_them = 830100026495336478
it_they = 846792150224994335
announcements = 831641701881217024
events = 831641733846401034
minecraft = 849105966473543690

[messages]
reaction = 458130425567641612

[emoji]
event = "\uD83E\uDD73"
announcement = "\uD83D\uDCE3"
minecraft = "minecraft"